### ISSUE TITLE
add event organiser.

### ISSUE THREAD

**Issue by maleroy2604** [Sreenadh1543/ogo-data-holder#10]
Is add event organiser is the same role as admin ?

**Comment by Sreenadh1543** [comment]
Dear ,

No , what i foresee is an admin who has master access over the system (Can adjust the already formed data if needed and change roles to that extent )
Event organizer just have access to read score provided by judges and download documents provided by team members and push notifications to teams , send reminders only to that extent .

Details we can refine along respective user stories
