### ISSUE TITLE
Score system.

### ISSUE THREAD

**Issue by maleroy2604** [Sreenadh1543/ogo-data-holder#12]
What are the attributes for the score system are they the same than leader board (viability etc ....) ?
As an idea we can take the speed interface as inspiration.

**Comment by Sreenadh1543** [comment]
Dear ,

Good idea , this article is my inspiration on parameters
i am flexible with GUI options 

https://medium.com/innovation-sweet-spot/desirability-feasibility-viability-the-sweet-spot-for-innovation-d7946de2183c
