### ISSUE TITLE
Event Registration as first step

### ISSUE THREAD

**Issue by NishaSingh1320** [Sreenadh1543/ogo-data-holder#8]
@Sreenadh1543 @ashokkannanvembu : Don't we need to support Event Registration first & then Participant Registration into respective events.  

- Event Registration
              Event Organizer
              Event Coordinator
              Evaluator
              Admin

- Participant Registration for Events
              PO
              SM & So on.......................

**Comment by Sreenadh1543** [comment]
Dear ,

As discussed during feature refinement , No 

we make just one registration possible to make the system simple
